import React from "react";
import { NextSeo } from "next-seo";
import Layout from "@/layouts/Layout";
import Hero from "@/components/Hero/Hero";
import Service from "@/components/Service/Service";
import CallUsBanner from "@/components/CallUsBanner/CallUsBanner";
import Portfolio from "@/components/Portfolio/Portfolio";
import About from "@/components/About/About";
import WarrantyBanner from "@/components/WarrantyBanner/WarrantyBanner";
import Contacts from "@/components/Contacts/Contacts";

const Home = () => {
  return (
    <>
      <NextSeo title="Floors" description="Generated by create next app" />
      <Layout>
        <Hero />
        <Service />
        <CallUsBanner />
        <Portfolio />
        <About />
        <WarrantyBanner />
        <Contacts />
      </Layout>
    </>
  );
};

export default Home;
