import React from "react";
import Head from "next/head";
import Topbar from "@/components/Header/Topbar";
import Navbar from "@/components/Header/Navbar";
import Hero from "@/components/Hero/Hero";
import Service from "@/components/Service/Service";
import CallUsBanner from "@/components/CallUsBanner/CallUsBanner";
import Portfolio from "@/components/Portfolio/Portfolio";
import About from "@/components/About/About";
import WarrantyBanner from "@/components/WarrantyBanner/WarrantyBanner";
import Contacts from "@/components/Contacts/Contacts";
import Footer from "@/components/Footer/Footer";

const Home = () => {
  return (
    <>
      <Head>
        <title>POL77</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Topbar />
        <Navbar />
        <Hero />
        <Service />
        <CallUsBanner />
        <Portfolio />
        <About />
        <WarrantyBanner />
        <Contacts />
      </main>
      <Footer />
    </>
  );
};

export default Home;
