import Head from "next/head";
import Topbar from "@/components/Header/Topbar";
import Navbar from "@/components/Header/Navbar";
import Hero from "@/components/Hero/Hero";
import Service from "@/components/Service/Service";


export default function Home() {
  return (
    <>
      <Head>
        <title>POL77</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Topbar />
        <Navbar />
        <Hero />
        <Service />


      </main>
      
    </>
  );
}
